export const locations = [
  { label: 'Administration Board Room', value: 1 },
  { label: 'Graff Classroom', value: 2 },
  { label: 'Graff Field', value: 3 },
  { label: 'Graff Gym', value: 4 },
  { label: 'Graff Cafeteria', value: 5 },
  { label: 'Graff Library', value: 6 },
  { label: 'LHS Auditorium', value: 7 },
  { label: 'LHS Band Room', value: 8 },
  { label: 'LHS Choir Room', value: 9 },
  { label: 'LHS Classroom-FACS', value: 10 },
  { label: 'LHS Classroom', value: 11 },
  { label: 'LHS Depot', value: 12 },
  { label: 'LHS Gym', value: 13 },
  { label: 'LHS Library', value: 14 },
  { label: 'LHS Parking Lot', value: 15 },
  { label: 'LHS Practice Field', value: 16 },
  { label: 'LMS Band Room', value: 17 },
  { label: 'LMS Classroom FACS', value: 18 },
  { label: 'LMS Classroom', value: 19 },
  { label: 'LMS Commons', value: 20 },
  { label: 'LMS Gym', value: 21 },
  { label: 'LMS Library', value: 22 },
  { label: 'LMS Mogan Field', value: 23 },
  { label: 'South Elementary Cafeteria', value: 24 },
  { label: 'South Elementary Baseball Field', value: 25 },
  { label: 'South Elementary Classroom', value: 26 },
  { label: 'ExampleSchool Stadium', value: 27 },
  { label: 'ExampleSchool Stadium Warming Rooms', value: 28 },
  { label: 'West Elementary Baseball Field', value: 29 },
  { label: 'West Elementary Classroom', value: 30 },
  { label: 'West Elementary Gym', value: 31 },
];
