version: '3.9'
services:
  frontend:
    image: docker.laurel.k12.mt.us/lps-facilities
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
