import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    AZURE_AD_CLIENT_ID: z.string(),
    AZURE_AD_CLIENT_SECRET: z.string(),
    AZURE_TENANT_ID: z.string(),
    AZURE_AUTHORITY: z.string(),
    RESET_SECRET: z.string(),
    NEXTAUTH_URL: z.string(),
    CAL_API_KEY: z.string(),
    RSA_PRIVATE_KEY: z.string(),
    RSA_PUBLIC_KEY: z.string(),
    DIRECT_URL: z.string(),
    DATABASE_URL: z.string(),
    CRON_SECRET: z.string(),
    SQUARE_API_ID: z.string(),
    GMAIL_USER: z.string(),
    GMAIL_PASSWORD: z.string(),
    HOSTNAME: z.string(),
    PORT: z.string(),
    HOST: z.string(),
    EMAIL_API_KEY: z.string(),
    SQUARE_APP_ID: z.string(),
    SQUARE_LOCATION_ID: z.string(),
    SQUARE_TOKEN: z.string(),
    GOOGLE_CAL_USER: z.string(),
    GOOGLE_CAL_PASS: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    GOOGLE_ACCESS_TOKEN: z.string(),
    GOOGLE_REFRESH_TOKEN: z.string(),
    GOOGLE_REDIRECT_URI: z.string(),
    GOOGLE_API_KEY: z.string(),
    S3_USER: z.string(),
    S3_PASSWORD: z.string(),
    S3_ACCESS_KEY: z.string(),
    S3_SECRET: z.string(),
    S3_HOST: z.string(),
    S3_URL: z.string(),
    RESEND_API: z.string(),
    BLOB_READ_WRITE_TOKEN: z.string(),
    GITHUB_TOKEN: z.string(),
  },
  client: {
    NEXT_PUBLIC_ENABLE_GOOGLE_AUTH: z.string(),
    NEXT_PUBLIC_ENABLE_AZURE_AUTH: z.string(),
    NEXT_PUBLIC_HOST: z.string(),
    NEXT_PUBLIC_EMAIL_API: z.string(),
    NEXT_PUBLIC_GA_TRACKING_ID: z.string(),
    NEXT_PUBLIC_GOOGLE_ANALYTICS: z.string(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_ENABLE_GOOGLE_AUTH: process.env.NEXT_PUBLIC_ENABLE_GOOGLE_AUTH,
    NEXT_PUBLIC_ENABLE_AZURE_AUTH: process.env.NEXT_PUBLIC_ENABLE_AZURE_AUTH,
    NEXT_PUBLIC_HOST: process.env.NEXT_PUBLIC_HOST,
    NEXT_PUBLIC_EMAIL_API: process.env.NEXT_PUBLIC_EMAIL_API,
    NEXT_PUBLIC_GA_TRACKING_ID: process.env.NEXT_PUBLIC_GA_TRACKING_ID,
    NEXT_PUBLIC_GOOGLE_ANALYTICS: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS,
  },
});
